### Site info:

title : Biology and Mathematics
tagline: To Infinity and Beyond!
author: Lijia YU
email: yu@lijiayu.net
description: "The English blog of Lijia Yu."
keywords: "genomics, bioinformatics, mathematics, statistics, perl, R language, data visualization, data analysis, LaTeX, Lijia Yu"
baseurl: "/en" # the subpath of your site, e.g. /blog/
url: "http://yulijia.net/en" # the base hostname & protocol for your site


### Personal info and site tools info:
twitter_username: yulijia
github_username:  yulijia
disqus_shortname: biologyandmathematics
favicon:     "/images/favicon.ico"
#touch_icon:  "img/apple-touch-icon.png"
#google_analytics_key: UA-49607422-1 # put YOUR key here to enable tracking! (blank to disable)
#aboutme: Hi, this is Lijia Yu.  # these are shown on aboutme-sidebar.
#aboutme_photo: https://i.imgur.com/15BT1.jpg # your photo.


### Site setting:
ShowContactInfo: "False" 
default_column: "one" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Resent_Posts: "Resent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Resent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "

### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: Yihui Xie's Blog       
      href: http://yihui.name      
      title: author of knitr, I think he is the Small Forward of R world now.

### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
